/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/kirillinda/provider-vcd/apis/vm/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this NetworkDHCPBinding.
func (mg *NetworkDHCPBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MacAddress),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.MacAddressRef,
		Selector:     mg.Spec.ForProvider.MacAddressSelector,
		To: reference.To{
			List:    &v1alpha1.VMList{},
			Managed: &v1alpha1.VM{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MacAddress")
	}
	mg.Spec.ForProvider.MacAddress = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MacAddressRef = rsp.ResolvedReference

	return nil
}
