//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPV4ConfigObservation) DeepCopyInto(out *DHCPV4ConfigObservation) {
	*out = *in
	if in.GatewayIPAddress != nil {
		in, out := &in.GatewayIPAddress, &out.GatewayIPAddress
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPV4ConfigObservation.
func (in *DHCPV4ConfigObservation) DeepCopy() *DHCPV4ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(DHCPV4ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPV4ConfigParameters) DeepCopyInto(out *DHCPV4ConfigParameters) {
	*out = *in
	if in.GatewayIPAddress != nil {
		in, out := &in.GatewayIPAddress, &out.GatewayIPAddress
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.HostnameRef != nil {
		in, out := &in.HostnameRef, &out.HostnameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.HostnameSelector != nil {
		in, out := &in.HostnameSelector, &out.HostnameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPV4ConfigParameters.
func (in *DHCPV4ConfigParameters) DeepCopy() *DHCPV4ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(DHCPV4ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPV6ConfigObservation) DeepCopyInto(out *DHCPV6ConfigObservation) {
	*out = *in
	if in.DomainNames != nil {
		in, out := &in.DomainNames, &out.DomainNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SntpServers != nil {
		in, out := &in.SntpServers, &out.SntpServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPV6ConfigObservation.
func (in *DHCPV6ConfigObservation) DeepCopy() *DHCPV6ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(DHCPV6ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPV6ConfigParameters) DeepCopyInto(out *DHCPV6ConfigParameters) {
	*out = *in
	if in.DomainNames != nil {
		in, out := &in.DomainNames, &out.DomainNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SntpServers != nil {
		in, out := &in.SntpServers, &out.SntpServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPV6ConfigParameters.
func (in *DHCPV6ConfigParameters) DeepCopy() *DHCPV6ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(DHCPV6ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDHCPBinding) DeepCopyInto(out *NetworkDHCPBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDHCPBinding.
func (in *NetworkDHCPBinding) DeepCopy() *NetworkDHCPBinding {
	if in == nil {
		return nil
	}
	out := new(NetworkDHCPBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkDHCPBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDHCPBindingList) DeepCopyInto(out *NetworkDHCPBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkDHCPBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDHCPBindingList.
func (in *NetworkDHCPBindingList) DeepCopy() *NetworkDHCPBindingList {
	if in == nil {
		return nil
	}
	out := new(NetworkDHCPBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkDHCPBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDHCPBindingObservation) DeepCopyInto(out *NetworkDHCPBindingObservation) {
	*out = *in
	if in.BindingType != nil {
		in, out := &in.BindingType, &out.BindingType
		*out = new(string)
		**out = **in
	}
	if in.DHCPV4Config != nil {
		in, out := &in.DHCPV4Config, &out.DHCPV4Config
		*out = make([]DHCPV4ConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DHCPV6Config != nil {
		in, out := &in.DHCPV6Config, &out.DHCPV6Config
		*out = make([]DHCPV6ConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNSServers != nil {
		in, out := &in.DNSServers, &out.DNSServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
	if in.LeaseTime != nil {
		in, out := &in.LeaseTime, &out.LeaseTime
		*out = new(float64)
		**out = **in
	}
	if in.MacAddress != nil {
		in, out := &in.MacAddress, &out.MacAddress
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.OrgNetworkID != nil {
		in, out := &in.OrgNetworkID, &out.OrgNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDHCPBindingObservation.
func (in *NetworkDHCPBindingObservation) DeepCopy() *NetworkDHCPBindingObservation {
	if in == nil {
		return nil
	}
	out := new(NetworkDHCPBindingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDHCPBindingParameters) DeepCopyInto(out *NetworkDHCPBindingParameters) {
	*out = *in
	if in.BindingType != nil {
		in, out := &in.BindingType, &out.BindingType
		*out = new(string)
		**out = **in
	}
	if in.DHCPV4Config != nil {
		in, out := &in.DHCPV4Config, &out.DHCPV4Config
		*out = make([]DHCPV4ConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DHCPV6Config != nil {
		in, out := &in.DHCPV6Config, &out.DHCPV6Config
		*out = make([]DHCPV6ConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNSServers != nil {
		in, out := &in.DNSServers, &out.DNSServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
	if in.LeaseTime != nil {
		in, out := &in.LeaseTime, &out.LeaseTime
		*out = new(float64)
		**out = **in
	}
	if in.MacAddress != nil {
		in, out := &in.MacAddress, &out.MacAddress
		*out = new(string)
		**out = **in
	}
	if in.MacAddressRef != nil {
		in, out := &in.MacAddressRef, &out.MacAddressRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.MacAddressSelector != nil {
		in, out := &in.MacAddressSelector, &out.MacAddressSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.OrgNetworkID != nil {
		in, out := &in.OrgNetworkID, &out.OrgNetworkID
		*out = new(string)
		**out = **in
	}
	if in.OrgNetworkIDRef != nil {
		in, out := &in.OrgNetworkIDRef, &out.OrgNetworkIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgNetworkIDSelector != nil {
		in, out := &in.OrgNetworkIDSelector, &out.OrgNetworkIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDHCPBindingParameters.
func (in *NetworkDHCPBindingParameters) DeepCopy() *NetworkDHCPBindingParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkDHCPBindingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDHCPBindingSpec) DeepCopyInto(out *NetworkDHCPBindingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDHCPBindingSpec.
func (in *NetworkDHCPBindingSpec) DeepCopy() *NetworkDHCPBindingSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkDHCPBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDHCPBindingStatus) DeepCopyInto(out *NetworkDHCPBindingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDHCPBindingStatus.
func (in *NetworkDHCPBindingStatus) DeepCopy() *NetworkDHCPBindingStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkDHCPBindingStatus)
	in.DeepCopyInto(out)
	return out
}
