/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DHCPV4ConfigObservation struct {

	// Gateway IP address to use for the client
	// IPv4 gateway address
	GatewayIPAddress *string `json:"gatewayIpAddress,omitempty" tf:"gateway_ip_address,omitempty"`

	// Hostname to be set for client
	// Hostname for the DHCP client
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`
}

type DHCPV4ConfigParameters struct {

	// Gateway IP address to use for the client
	// IPv4 gateway address
	// +kubebuilder:validation:Optional
	GatewayIPAddress *string `json:"gatewayIpAddress,omitempty" tf:"gateway_ip_address,omitempty"`

	// Hostname to be set for client
	// Hostname for the DHCP client
	// +crossplane:generate:reference:type=github.com/kirillinda/provider-vcd/apis/vm/v1alpha1.VM
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("computer_name", true)
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Reference to a VM in vm to populate hostname.
	// +kubebuilder:validation:Optional
	HostnameRef *v1.Reference `json:"hostnameRef,omitempty" tf:"-"`

	// Selector for a VM in vm to populate hostname.
	// +kubebuilder:validation:Optional
	HostnameSelector *v1.Selector `json:"hostnameSelector,omitempty" tf:"-"`
}

type DHCPV6ConfigObservation struct {

	// A set of domain names
	// Set of domain names
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// A set of SNTP servers
	// Set of SNTP servers
	SntpServers []*string `json:"sntpServers,omitempty" tf:"sntp_servers,omitempty"`
}

type DHCPV6ConfigParameters struct {

	// A set of domain names
	// Set of domain names
	// +kubebuilder:validation:Optional
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// A set of SNTP servers
	// Set of SNTP servers
	// +kubebuilder:validation:Optional
	SntpServers []*string `json:"sntpServers,omitempty" tf:"sntp_servers,omitempty"`
}

type NetworkDHCPBindingObservation struct {

	// One of IPV4 or IPV6
	// Binding type 'IPV4' or 'IPV6'
	BindingType *string `json:"bindingType,omitempty" tf:"binding_type,omitempty"`

	// Additional configuration for IPv4 specific options. See IPv4 block
	// IPv4 specific DHCP Binding configuration
	DHCPV4Config []DHCPV4ConfigObservation `json:"dhcpV4Config,omitempty" tf:"dhcp_v4_config,omitempty"`

	// Additional configuration for IPv6 specific options. See IPv6 block
	// IPv6 specific DHCP Binding configuration
	DHCPV6Config []DHCPV6ConfigObservation `json:"dhcpV6Config,omitempty" tf:"dhcp_v6_config,omitempty"`

	// A list of DNS servers. Maximum 2 can be specified
	// The DNS server IPs to be assigned . 2 values maximum.
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// Description of DHCP binding
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP address used for binding
	// IP address of the DHCP binding
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// Lease time in seconds. Minimum 3600 seconds
	// Lease time in seconds. Minimum value is 60 seconds
	LeaseTime *float64 `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// MAC address used for binding
	// MAC address of the DHCP binding
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// Name of DHCP binding
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization. Optional if defined at provider level
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// The ID of an Org VDC network. Note  (.id field) of
	// vcd_network_isolated_v2, vcd_network_routed_v2 or vcd_nsxt_network_dhcp can be referenced
	// here. It is more convenient to use reference to vcd_nsxt_network_dhcp ID because it makes sure
	// that DHCP is enabled before configuring pools
	// Parent Org VDC network ID
	OrgNetworkID *string `json:"orgNetworkId,omitempty" tf:"org_network_id,omitempty"`
}

type NetworkDHCPBindingParameters struct {

	// One of IPV4 or IPV6
	// Binding type 'IPV4' or 'IPV6'
	// +kubebuilder:validation:Optional
	BindingType *string `json:"bindingType,omitempty" tf:"binding_type,omitempty"`

	// Additional configuration for IPv4 specific options. See IPv4 block
	// IPv4 specific DHCP Binding configuration
	// +kubebuilder:validation:Optional
	DHCPV4Config []DHCPV4ConfigParameters `json:"dhcpV4Config,omitempty" tf:"dhcp_v4_config,omitempty"`

	// Additional configuration for IPv6 specific options. See IPv6 block
	// IPv6 specific DHCP Binding configuration
	// +kubebuilder:validation:Optional
	DHCPV6Config []DHCPV6ConfigParameters `json:"dhcpV6Config,omitempty" tf:"dhcp_v6_config,omitempty"`

	// A list of DNS servers. Maximum 2 can be specified
	// The DNS server IPs to be assigned . 2 values maximum.
	// +kubebuilder:validation:Optional
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// Description of DHCP binding
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// IP address used for binding
	// IP address of the DHCP binding
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// Lease time in seconds. Minimum 3600 seconds
	// Lease time in seconds. Minimum value is 60 seconds
	// +kubebuilder:validation:Optional
	LeaseTime *float64 `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// MAC address used for binding
	// MAC address of the DHCP binding
	// +crossplane:generate:reference:type=github.com/kirillinda/provider-vcd/apis/vm/v1alpha1.VM
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("network[0].mac", true)
	// +kubebuilder:validation:Optional
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// Reference to a VM in vm to populate macAddress.
	// +kubebuilder:validation:Optional
	MacAddressRef *v1.Reference `json:"macAddressRef,omitempty" tf:"-"`

	// Selector for a VM in vm to populate macAddress.
	// +kubebuilder:validation:Optional
	MacAddressSelector *v1.Selector `json:"macAddressSelector,omitempty" tf:"-"`

	// Name of DHCP binding
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization. Optional if defined at provider level
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// The ID of an Org VDC network. Note  (.id field) of
	// vcd_network_isolated_v2, vcd_network_routed_v2 or vcd_nsxt_network_dhcp can be referenced
	// here. It is more convenient to use reference to vcd_nsxt_network_dhcp ID because it makes sure
	// that DHCP is enabled before configuring pools
	// Parent Org VDC network ID
	// +crossplane:generate:reference:type=github.com/kirillinda/provider-vcd/apis/vcdnetworkroutedv2/v1alpha1.RoutedV2
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	OrgNetworkID *string `json:"orgNetworkId,omitempty" tf:"org_network_id,omitempty"`

	// Reference to a RoutedV2 in vcdnetworkroutedv2 to populate orgNetworkId.
	// +kubebuilder:validation:Optional
	OrgNetworkIDRef *v1.Reference `json:"orgNetworkIdRef,omitempty" tf:"-"`

	// Selector for a RoutedV2 in vcdnetworkroutedv2 to populate orgNetworkId.
	// +kubebuilder:validation:Optional
	OrgNetworkIDSelector *v1.Selector `json:"orgNetworkIdSelector,omitempty" tf:"-"`
}

// NetworkDHCPBindingSpec defines the desired state of NetworkDHCPBinding
type NetworkDHCPBindingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkDHCPBindingParameters `json:"forProvider"`
}

// NetworkDHCPBindingStatus defines the observed state of NetworkDHCPBinding.
type NetworkDHCPBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkDHCPBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkDHCPBinding is the Schema for the NetworkDHCPBindings API. Provides a resource to manage NSX-T Org VDC network DHCP bindings.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NetworkDHCPBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.bindingType)",message="bindingType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.ipAddress)",message="ipAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.leaseTime)",message="leaseTime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	Spec   NetworkDHCPBindingSpec   `json:"spec"`
	Status NetworkDHCPBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkDHCPBindingList contains a list of NetworkDHCPBindings
type NetworkDHCPBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkDHCPBinding `json:"items"`
}

// Repository type metadata.
var (
	NetworkDHCPBinding_Kind             = "NetworkDHCPBinding"
	NetworkDHCPBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkDHCPBinding_Kind}.String()
	NetworkDHCPBinding_KindAPIVersion   = NetworkDHCPBinding_Kind + "." + CRDGroupVersion.String()
	NetworkDHCPBinding_GroupVersionKind = CRDGroupVersion.WithKind(NetworkDHCPBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkDHCPBinding{}, &NetworkDHCPBindingList{})
}
