//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDisk) DeepCopyInto(out *InternalDisk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDisk.
func (in *InternalDisk) DeepCopy() *InternalDisk {
	if in == nil {
		return nil
	}
	out := new(InternalDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InternalDisk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDiskList) DeepCopyInto(out *InternalDiskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InternalDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDiskList.
func (in *InternalDiskList) DeepCopy() *InternalDiskList {
	if in == nil {
		return nil
	}
	out := new(InternalDiskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InternalDiskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDiskObservation) DeepCopyInto(out *InternalDiskObservation) {
	*out = *in
	if in.AllowVMReboot != nil {
		in, out := &in.AllowVMReboot, &out.AllowVMReboot
		*out = new(bool)
		**out = **in
	}
	if in.BusNumber != nil {
		in, out := &in.BusNumber, &out.BusNumber
		*out = new(float64)
		**out = **in
	}
	if in.BusType != nil {
		in, out := &in.BusType, &out.BusType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Iops != nil {
		in, out := &in.Iops, &out.Iops
		*out = new(float64)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.SizeInMb != nil {
		in, out := &in.SizeInMb, &out.SizeInMb
		*out = new(float64)
		**out = **in
	}
	if in.StorageProfile != nil {
		in, out := &in.StorageProfile, &out.StorageProfile
		*out = new(string)
		**out = **in
	}
	if in.ThinProvisioned != nil {
		in, out := &in.ThinProvisioned, &out.ThinProvisioned
		*out = new(bool)
		**out = **in
	}
	if in.UnitNumber != nil {
		in, out := &in.UnitNumber, &out.UnitNumber
		*out = new(float64)
		**out = **in
	}
	if in.VMName != nil {
		in, out := &in.VMName, &out.VMName
		*out = new(string)
		**out = **in
	}
	if in.VappName != nil {
		in, out := &in.VappName, &out.VappName
		*out = new(string)
		**out = **in
	}
	if in.Vdc != nil {
		in, out := &in.Vdc, &out.Vdc
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDiskObservation.
func (in *InternalDiskObservation) DeepCopy() *InternalDiskObservation {
	if in == nil {
		return nil
	}
	out := new(InternalDiskObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDiskParameters) DeepCopyInto(out *InternalDiskParameters) {
	*out = *in
	if in.AllowVMReboot != nil {
		in, out := &in.AllowVMReboot, &out.AllowVMReboot
		*out = new(bool)
		**out = **in
	}
	if in.BusNumber != nil {
		in, out := &in.BusNumber, &out.BusNumber
		*out = new(float64)
		**out = **in
	}
	if in.BusType != nil {
		in, out := &in.BusType, &out.BusType
		*out = new(string)
		**out = **in
	}
	if in.Iops != nil {
		in, out := &in.Iops, &out.Iops
		*out = new(float64)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.SizeInMb != nil {
		in, out := &in.SizeInMb, &out.SizeInMb
		*out = new(float64)
		**out = **in
	}
	if in.StorageProfile != nil {
		in, out := &in.StorageProfile, &out.StorageProfile
		*out = new(string)
		**out = **in
	}
	if in.UnitNumber != nil {
		in, out := &in.UnitNumber, &out.UnitNumber
		*out = new(float64)
		**out = **in
	}
	if in.VMName != nil {
		in, out := &in.VMName, &out.VMName
		*out = new(string)
		**out = **in
	}
	if in.VappName != nil {
		in, out := &in.VappName, &out.VappName
		*out = new(string)
		**out = **in
	}
	if in.Vdc != nil {
		in, out := &in.Vdc, &out.Vdc
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDiskParameters.
func (in *InternalDiskParameters) DeepCopy() *InternalDiskParameters {
	if in == nil {
		return nil
	}
	out := new(InternalDiskParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDiskSpec) DeepCopyInto(out *InternalDiskSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDiskSpec.
func (in *InternalDiskSpec) DeepCopy() *InternalDiskSpec {
	if in == nil {
		return nil
	}
	out := new(InternalDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDiskStatus) DeepCopyInto(out *InternalDiskStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDiskStatus.
func (in *InternalDiskStatus) DeepCopy() *InternalDiskStatus {
	if in == nil {
		return nil
	}
	out := new(InternalDiskStatus)
	in.DeepCopyInto(out)
	return out
}
