/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/kirillinda/provider-vcd/apis/vcdnetworkroutedv2/v1alpha1"
	errors "github.com/pkg/errors"
	resource "github.com/upbound/upjet/pkg/resource"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this NetworkDHCP.
func (mg *NetworkDHCP) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgNetworkID),
		Extract:      resource.ExtractParamPath("id", true),
		Reference:    mg.Spec.ForProvider.OrgNetworkIDRef,
		Selector:     mg.Spec.ForProvider.OrgNetworkIDSelector,
		To: reference.To{
			List:    &v1alpha1.RoutedV2List{},
			Managed: &v1alpha1.RoutedV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgNetworkID")
	}
	mg.Spec.ForProvider.OrgNetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgNetworkIDRef = rsp.ResolvedReference

	return nil
}
