//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationObservation) DeepCopyInto(out *CustomizationObservation) {
	*out = *in
	if in.AllowLocalAdminPassword != nil {
		in, out := &in.AllowLocalAdminPassword, &out.AllowLocalAdminPassword
		*out = new(bool)
		**out = **in
	}
	if in.AutoGeneratePassword != nil {
		in, out := &in.AutoGeneratePassword, &out.AutoGeneratePassword
		*out = new(bool)
		**out = **in
	}
	if in.ChangeSid != nil {
		in, out := &in.ChangeSid, &out.ChangeSid
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Force != nil {
		in, out := &in.Force, &out.Force
		*out = new(bool)
		**out = **in
	}
	if in.Initscript != nil {
		in, out := &in.Initscript, &out.Initscript
		*out = new(string)
		**out = **in
	}
	if in.JoinDomain != nil {
		in, out := &in.JoinDomain, &out.JoinDomain
		*out = new(bool)
		**out = **in
	}
	if in.JoinDomainAccountOu != nil {
		in, out := &in.JoinDomainAccountOu, &out.JoinDomainAccountOu
		*out = new(string)
		**out = **in
	}
	if in.JoinDomainName != nil {
		in, out := &in.JoinDomainName, &out.JoinDomainName
		*out = new(string)
		**out = **in
	}
	if in.JoinDomainUser != nil {
		in, out := &in.JoinDomainUser, &out.JoinDomainUser
		*out = new(string)
		**out = **in
	}
	if in.JoinOrgDomain != nil {
		in, out := &in.JoinOrgDomain, &out.JoinOrgDomain
		*out = new(bool)
		**out = **in
	}
	if in.MustChangePasswordOnFirstLogin != nil {
		in, out := &in.MustChangePasswordOnFirstLogin, &out.MustChangePasswordOnFirstLogin
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfAutoLogons != nil {
		in, out := &in.NumberOfAutoLogons, &out.NumberOfAutoLogons
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationObservation.
func (in *CustomizationObservation) DeepCopy() *CustomizationObservation {
	if in == nil {
		return nil
	}
	out := new(CustomizationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationParameters) DeepCopyInto(out *CustomizationParameters) {
	*out = *in
	if in.AdminPasswordSecretRef != nil {
		in, out := &in.AdminPasswordSecretRef, &out.AdminPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AllowLocalAdminPassword != nil {
		in, out := &in.AllowLocalAdminPassword, &out.AllowLocalAdminPassword
		*out = new(bool)
		**out = **in
	}
	if in.AutoGeneratePassword != nil {
		in, out := &in.AutoGeneratePassword, &out.AutoGeneratePassword
		*out = new(bool)
		**out = **in
	}
	if in.ChangeSid != nil {
		in, out := &in.ChangeSid, &out.ChangeSid
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Force != nil {
		in, out := &in.Force, &out.Force
		*out = new(bool)
		**out = **in
	}
	if in.Initscript != nil {
		in, out := &in.Initscript, &out.Initscript
		*out = new(string)
		**out = **in
	}
	if in.JoinDomain != nil {
		in, out := &in.JoinDomain, &out.JoinDomain
		*out = new(bool)
		**out = **in
	}
	if in.JoinDomainAccountOu != nil {
		in, out := &in.JoinDomainAccountOu, &out.JoinDomainAccountOu
		*out = new(string)
		**out = **in
	}
	if in.JoinDomainName != nil {
		in, out := &in.JoinDomainName, &out.JoinDomainName
		*out = new(string)
		**out = **in
	}
	if in.JoinDomainPasswordSecretRef != nil {
		in, out := &in.JoinDomainPasswordSecretRef, &out.JoinDomainPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.JoinDomainUser != nil {
		in, out := &in.JoinDomainUser, &out.JoinDomainUser
		*out = new(string)
		**out = **in
	}
	if in.JoinOrgDomain != nil {
		in, out := &in.JoinOrgDomain, &out.JoinOrgDomain
		*out = new(bool)
		**out = **in
	}
	if in.MustChangePasswordOnFirstLogin != nil {
		in, out := &in.MustChangePasswordOnFirstLogin, &out.MustChangePasswordOnFirstLogin
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfAutoLogons != nil {
		in, out := &in.NumberOfAutoLogons, &out.NumberOfAutoLogons
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationParameters.
func (in *CustomizationParameters) DeepCopy() *CustomizationParameters {
	if in == nil {
		return nil
	}
	out := new(CustomizationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskObservation) DeepCopyInto(out *DiskObservation) {
	*out = *in
	if in.BusNumber != nil {
		in, out := &in.BusNumber, &out.BusNumber
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SizeInMb != nil {
		in, out := &in.SizeInMb, &out.SizeInMb
		*out = new(float64)
		**out = **in
	}
	if in.UnitNumber != nil {
		in, out := &in.UnitNumber, &out.UnitNumber
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskObservation.
func (in *DiskObservation) DeepCopy() *DiskObservation {
	if in == nil {
		return nil
	}
	out := new(DiskObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskParameters) DeepCopyInto(out *DiskParameters) {
	*out = *in
	if in.BusNumber != nil {
		in, out := &in.BusNumber, &out.BusNumber
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameRef != nil {
		in, out := &in.NameRef, &out.NameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.NameSelector != nil {
		in, out := &in.NameSelector, &out.NameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.UnitNumber != nil {
		in, out := &in.UnitNumber, &out.UnitNumber
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskParameters.
func (in *DiskParameters) DeepCopy() *DiskParameters {
	if in == nil {
		return nil
	}
	out := new(DiskParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDiskObservation) DeepCopyInto(out *InternalDiskObservation) {
	*out = *in
	if in.BusNumber != nil {
		in, out := &in.BusNumber, &out.BusNumber
		*out = new(float64)
		**out = **in
	}
	if in.BusType != nil {
		in, out := &in.BusType, &out.BusType
		*out = new(string)
		**out = **in
	}
	if in.DiskID != nil {
		in, out := &in.DiskID, &out.DiskID
		*out = new(string)
		**out = **in
	}
	if in.Iops != nil {
		in, out := &in.Iops, &out.Iops
		*out = new(float64)
		**out = **in
	}
	if in.SizeInMb != nil {
		in, out := &in.SizeInMb, &out.SizeInMb
		*out = new(float64)
		**out = **in
	}
	if in.StorageProfile != nil {
		in, out := &in.StorageProfile, &out.StorageProfile
		*out = new(string)
		**out = **in
	}
	if in.ThinProvisioned != nil {
		in, out := &in.ThinProvisioned, &out.ThinProvisioned
		*out = new(bool)
		**out = **in
	}
	if in.UnitNumber != nil {
		in, out := &in.UnitNumber, &out.UnitNumber
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDiskObservation.
func (in *InternalDiskObservation) DeepCopy() *InternalDiskObservation {
	if in == nil {
		return nil
	}
	out := new(InternalDiskObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDiskParameters) DeepCopyInto(out *InternalDiskParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDiskParameters.
func (in *InternalDiskParameters) DeepCopy() *InternalDiskParameters {
	if in == nil {
		return nil
	}
	out := new(InternalDiskParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataEntryObservation) DeepCopyInto(out *MetadataEntryObservation) {
	*out = *in
	if in.IsSystem != nil {
		in, out := &in.IsSystem, &out.IsSystem
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserAccess != nil {
		in, out := &in.UserAccess, &out.UserAccess
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataEntryObservation.
func (in *MetadataEntryObservation) DeepCopy() *MetadataEntryObservation {
	if in == nil {
		return nil
	}
	out := new(MetadataEntryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataEntryParameters) DeepCopyInto(out *MetadataEntryParameters) {
	*out = *in
	if in.IsSystem != nil {
		in, out := &in.IsSystem, &out.IsSystem
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserAccess != nil {
		in, out := &in.UserAccess, &out.UserAccess
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataEntryParameters.
func (in *MetadataEntryParameters) DeepCopy() *MetadataEntryParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataEntryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkObservation) DeepCopyInto(out *NetworkObservation) {
	*out = *in
	if in.AdapterType != nil {
		in, out := &in.AdapterType, &out.AdapterType
		*out = new(string)
		**out = **in
	}
	if in.Connected != nil {
		in, out := &in.Connected, &out.Connected
		*out = new(bool)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.IPAllocationMode != nil {
		in, out := &in.IPAllocationMode, &out.IPAllocationMode
		*out = new(string)
		**out = **in
	}
	if in.IsPrimary != nil {
		in, out := &in.IsPrimary, &out.IsPrimary
		*out = new(bool)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkObservation.
func (in *NetworkObservation) DeepCopy() *NetworkObservation {
	if in == nil {
		return nil
	}
	out := new(NetworkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkParameters) DeepCopyInto(out *NetworkParameters) {
	*out = *in
	if in.AdapterType != nil {
		in, out := &in.AdapterType, &out.AdapterType
		*out = new(string)
		**out = **in
	}
	if in.Connected != nil {
		in, out := &in.Connected, &out.Connected
		*out = new(bool)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.IPAllocationMode != nil {
		in, out := &in.IPAllocationMode, &out.IPAllocationMode
		*out = new(string)
		**out = **in
	}
	if in.IsPrimary != nil {
		in, out := &in.IsPrimary, &out.IsPrimary
		*out = new(bool)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameRef != nil {
		in, out := &in.NameRef, &out.NameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.NameSelector != nil {
		in, out := &in.NameSelector, &out.NameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkParameters.
func (in *NetworkParameters) DeepCopy() *NetworkParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverrideTemplateDiskObservation) DeepCopyInto(out *OverrideTemplateDiskObservation) {
	*out = *in
	if in.BusNumber != nil {
		in, out := &in.BusNumber, &out.BusNumber
		*out = new(float64)
		**out = **in
	}
	if in.BusType != nil {
		in, out := &in.BusType, &out.BusType
		*out = new(string)
		**out = **in
	}
	if in.Iops != nil {
		in, out := &in.Iops, &out.Iops
		*out = new(float64)
		**out = **in
	}
	if in.SizeInMb != nil {
		in, out := &in.SizeInMb, &out.SizeInMb
		*out = new(float64)
		**out = **in
	}
	if in.StorageProfile != nil {
		in, out := &in.StorageProfile, &out.StorageProfile
		*out = new(string)
		**out = **in
	}
	if in.UnitNumber != nil {
		in, out := &in.UnitNumber, &out.UnitNumber
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverrideTemplateDiskObservation.
func (in *OverrideTemplateDiskObservation) DeepCopy() *OverrideTemplateDiskObservation {
	if in == nil {
		return nil
	}
	out := new(OverrideTemplateDiskObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverrideTemplateDiskParameters) DeepCopyInto(out *OverrideTemplateDiskParameters) {
	*out = *in
	if in.BusNumber != nil {
		in, out := &in.BusNumber, &out.BusNumber
		*out = new(float64)
		**out = **in
	}
	if in.BusType != nil {
		in, out := &in.BusType, &out.BusType
		*out = new(string)
		**out = **in
	}
	if in.Iops != nil {
		in, out := &in.Iops, &out.Iops
		*out = new(float64)
		**out = **in
	}
	if in.SizeInMb != nil {
		in, out := &in.SizeInMb, &out.SizeInMb
		*out = new(float64)
		**out = **in
	}
	if in.StorageProfile != nil {
		in, out := &in.StorageProfile, &out.StorageProfile
		*out = new(string)
		**out = **in
	}
	if in.UnitNumber != nil {
		in, out := &in.UnitNumber, &out.UnitNumber
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverrideTemplateDiskParameters.
func (in *OverrideTemplateDiskParameters) DeepCopy() *OverrideTemplateDiskParameters {
	if in == nil {
		return nil
	}
	out := new(OverrideTemplateDiskParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VM) DeepCopyInto(out *VM) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VM.
func (in *VM) DeepCopy() *VM {
	if in == nil {
		return nil
	}
	out := new(VM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VM) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMList) DeepCopyInto(out *VMList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMList.
func (in *VMList) DeepCopy() *VMList {
	if in == nil {
		return nil
	}
	out := new(VMList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMObservation) DeepCopyInto(out *VMObservation) {
	*out = *in
	if in.AcceptAllEulas != nil {
		in, out := &in.AcceptAllEulas, &out.AcceptAllEulas
		*out = new(bool)
		**out = **in
	}
	if in.BootImage != nil {
		in, out := &in.BootImage, &out.BootImage
		*out = new(string)
		**out = **in
	}
	if in.BootImageID != nil {
		in, out := &in.BootImageID, &out.BootImageID
		*out = new(string)
		**out = **in
	}
	if in.CPUCores != nil {
		in, out := &in.CPUCores, &out.CPUCores
		*out = new(float64)
		**out = **in
	}
	if in.CPUHotAddEnabled != nil {
		in, out := &in.CPUHotAddEnabled, &out.CPUHotAddEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CPULimit != nil {
		in, out := &in.CPULimit, &out.CPULimit
		*out = new(float64)
		**out = **in
	}
	if in.CPUPriority != nil {
		in, out := &in.CPUPriority, &out.CPUPriority
		*out = new(string)
		**out = **in
	}
	if in.CPUReservation != nil {
		in, out := &in.CPUReservation, &out.CPUReservation
		*out = new(float64)
		**out = **in
	}
	if in.CPUShares != nil {
		in, out := &in.CPUShares, &out.CPUShares
		*out = new(float64)
		**out = **in
	}
	if in.CatalogName != nil {
		in, out := &in.CatalogName, &out.CatalogName
		*out = new(string)
		**out = **in
	}
	if in.ComputerName != nil {
		in, out := &in.ComputerName, &out.ComputerName
		*out = new(string)
		**out = **in
	}
	if in.Cpus != nil {
		in, out := &in.Cpus, &out.Cpus
		*out = new(float64)
		**out = **in
	}
	if in.Customization != nil {
		in, out := &in.Customization, &out.Customization
		*out = make([]CustomizationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = make([]DiskObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExposeHardwareVirtualization != nil {
		in, out := &in.ExposeHardwareVirtualization, &out.ExposeHardwareVirtualization
		*out = new(bool)
		**out = **in
	}
	if in.GuestProperties != nil {
		in, out := &in.GuestProperties, &out.GuestProperties
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.HardwareVersion != nil {
		in, out := &in.HardwareVersion, &out.HardwareVersion
		*out = new(string)
		**out = **in
	}
	if in.Href != nil {
		in, out := &in.Href, &out.Href
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InternalDisk != nil {
		in, out := &in.InternalDisk, &out.InternalDisk
		*out = make([]InternalDiskObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(float64)
		**out = **in
	}
	if in.MemoryHotAddEnabled != nil {
		in, out := &in.MemoryHotAddEnabled, &out.MemoryHotAddEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MemoryLimit != nil {
		in, out := &in.MemoryLimit, &out.MemoryLimit
		*out = new(float64)
		**out = **in
	}
	if in.MemoryPriority != nil {
		in, out := &in.MemoryPriority, &out.MemoryPriority
		*out = new(string)
		**out = **in
	}
	if in.MemoryReservation != nil {
		in, out := &in.MemoryReservation, &out.MemoryReservation
		*out = new(float64)
		**out = **in
	}
	if in.MemoryShares != nil {
		in, out := &in.MemoryShares, &out.MemoryShares
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.MetadataEntry != nil {
		in, out := &in.MetadataEntry, &out.MetadataEntry
		*out = make([]MetadataEntryObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]NetworkObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkDHCPWaitSeconds != nil {
		in, out := &in.NetworkDHCPWaitSeconds, &out.NetworkDHCPWaitSeconds
		*out = new(float64)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.OsType != nil {
		in, out := &in.OsType, &out.OsType
		*out = new(string)
		**out = **in
	}
	if in.OverrideTemplateDisk != nil {
		in, out := &in.OverrideTemplateDisk, &out.OverrideTemplateDisk
		*out = make([]OverrideTemplateDiskObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PlacementPolicyID != nil {
		in, out := &in.PlacementPolicyID, &out.PlacementPolicyID
		*out = new(string)
		**out = **in
	}
	if in.PowerOn != nil {
		in, out := &in.PowerOn, &out.PowerOn
		*out = new(bool)
		**out = **in
	}
	if in.PreventUpdatePowerOff != nil {
		in, out := &in.PreventUpdatePowerOff, &out.PreventUpdatePowerOff
		*out = new(bool)
		**out = **in
	}
	if in.SecurityTags != nil {
		in, out := &in.SecurityTags, &out.SecurityTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SizingPolicyID != nil {
		in, out := &in.SizingPolicyID, &out.SizingPolicyID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(float64)
		**out = **in
	}
	if in.StatusText != nil {
		in, out := &in.StatusText, &out.StatusText
		*out = new(string)
		**out = **in
	}
	if in.StorageProfile != nil {
		in, out := &in.StorageProfile, &out.StorageProfile
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.VMNameInTemplate != nil {
		in, out := &in.VMNameInTemplate, &out.VMNameInTemplate
		*out = new(string)
		**out = **in
	}
	if in.VMType != nil {
		in, out := &in.VMType, &out.VMType
		*out = new(string)
		**out = **in
	}
	if in.VappName != nil {
		in, out := &in.VappName, &out.VappName
		*out = new(string)
		**out = **in
	}
	if in.VappTemplateID != nil {
		in, out := &in.VappTemplateID, &out.VappTemplateID
		*out = new(string)
		**out = **in
	}
	if in.Vdc != nil {
		in, out := &in.Vdc, &out.Vdc
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMObservation.
func (in *VMObservation) DeepCopy() *VMObservation {
	if in == nil {
		return nil
	}
	out := new(VMObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMParameters) DeepCopyInto(out *VMParameters) {
	*out = *in
	if in.AcceptAllEulas != nil {
		in, out := &in.AcceptAllEulas, &out.AcceptAllEulas
		*out = new(bool)
		**out = **in
	}
	if in.BootImage != nil {
		in, out := &in.BootImage, &out.BootImage
		*out = new(string)
		**out = **in
	}
	if in.BootImageID != nil {
		in, out := &in.BootImageID, &out.BootImageID
		*out = new(string)
		**out = **in
	}
	if in.CPUCores != nil {
		in, out := &in.CPUCores, &out.CPUCores
		*out = new(float64)
		**out = **in
	}
	if in.CPUHotAddEnabled != nil {
		in, out := &in.CPUHotAddEnabled, &out.CPUHotAddEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CPULimit != nil {
		in, out := &in.CPULimit, &out.CPULimit
		*out = new(float64)
		**out = **in
	}
	if in.CPUPriority != nil {
		in, out := &in.CPUPriority, &out.CPUPriority
		*out = new(string)
		**out = **in
	}
	if in.CPUReservation != nil {
		in, out := &in.CPUReservation, &out.CPUReservation
		*out = new(float64)
		**out = **in
	}
	if in.CPUShares != nil {
		in, out := &in.CPUShares, &out.CPUShares
		*out = new(float64)
		**out = **in
	}
	if in.CatalogName != nil {
		in, out := &in.CatalogName, &out.CatalogName
		*out = new(string)
		**out = **in
	}
	if in.ComputerName != nil {
		in, out := &in.ComputerName, &out.ComputerName
		*out = new(string)
		**out = **in
	}
	if in.Cpus != nil {
		in, out := &in.Cpus, &out.Cpus
		*out = new(float64)
		**out = **in
	}
	if in.Customization != nil {
		in, out := &in.Customization, &out.Customization
		*out = make([]CustomizationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = make([]DiskParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExposeHardwareVirtualization != nil {
		in, out := &in.ExposeHardwareVirtualization, &out.ExposeHardwareVirtualization
		*out = new(bool)
		**out = **in
	}
	if in.GuestProperties != nil {
		in, out := &in.GuestProperties, &out.GuestProperties
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.HardwareVersion != nil {
		in, out := &in.HardwareVersion, &out.HardwareVersion
		*out = new(string)
		**out = **in
	}
	if in.Href != nil {
		in, out := &in.Href, &out.Href
		*out = new(string)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(float64)
		**out = **in
	}
	if in.MemoryHotAddEnabled != nil {
		in, out := &in.MemoryHotAddEnabled, &out.MemoryHotAddEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MemoryLimit != nil {
		in, out := &in.MemoryLimit, &out.MemoryLimit
		*out = new(float64)
		**out = **in
	}
	if in.MemoryPriority != nil {
		in, out := &in.MemoryPriority, &out.MemoryPriority
		*out = new(string)
		**out = **in
	}
	if in.MemoryReservation != nil {
		in, out := &in.MemoryReservation, &out.MemoryReservation
		*out = new(float64)
		**out = **in
	}
	if in.MemoryShares != nil {
		in, out := &in.MemoryShares, &out.MemoryShares
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.MetadataEntry != nil {
		in, out := &in.MetadataEntry, &out.MetadataEntry
		*out = make([]MetadataEntryParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]NetworkParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkDHCPWaitSeconds != nil {
		in, out := &in.NetworkDHCPWaitSeconds, &out.NetworkDHCPWaitSeconds
		*out = new(float64)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.OsType != nil {
		in, out := &in.OsType, &out.OsType
		*out = new(string)
		**out = **in
	}
	if in.OverrideTemplateDisk != nil {
		in, out := &in.OverrideTemplateDisk, &out.OverrideTemplateDisk
		*out = make([]OverrideTemplateDiskParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PlacementPolicyID != nil {
		in, out := &in.PlacementPolicyID, &out.PlacementPolicyID
		*out = new(string)
		**out = **in
	}
	if in.PowerOn != nil {
		in, out := &in.PowerOn, &out.PowerOn
		*out = new(bool)
		**out = **in
	}
	if in.PreventUpdatePowerOff != nil {
		in, out := &in.PreventUpdatePowerOff, &out.PreventUpdatePowerOff
		*out = new(bool)
		**out = **in
	}
	if in.SecurityTags != nil {
		in, out := &in.SecurityTags, &out.SecurityTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SizingPolicyID != nil {
		in, out := &in.SizingPolicyID, &out.SizingPolicyID
		*out = new(string)
		**out = **in
	}
	if in.StorageProfile != nil {
		in, out := &in.StorageProfile, &out.StorageProfile
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.VMNameInTemplate != nil {
		in, out := &in.VMNameInTemplate, &out.VMNameInTemplate
		*out = new(string)
		**out = **in
	}
	if in.VappName != nil {
		in, out := &in.VappName, &out.VappName
		*out = new(string)
		**out = **in
	}
	if in.VappTemplateID != nil {
		in, out := &in.VappTemplateID, &out.VappTemplateID
		*out = new(string)
		**out = **in
	}
	if in.Vdc != nil {
		in, out := &in.Vdc, &out.Vdc
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMParameters.
func (in *VMParameters) DeepCopy() *VMParameters {
	if in == nil {
		return nil
	}
	out := new(VMParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMSpec) DeepCopyInto(out *VMSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMSpec.
func (in *VMSpec) DeepCopy() *VMSpec {
	if in == nil {
		return nil
	}
	out := new(VMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMStatus) DeepCopyInto(out *VMStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMStatus.
func (in *VMStatus) DeepCopy() *VMStatus {
	if in == nil {
		return nil
	}
	out := new(VMStatus)
	in.DeepCopyInto(out)
	return out
}
